[project]
name = "call-me-maybe-1337"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.13.4",
    "numpy>=2.2.6",
    "flake8>=7.3.0",
    "mypy>=1.17.0",
    "llm_sdk"
]

[tool.uv.sources]
llm_sdk = {workspace = true}

[tool.mypy]
python_version = "3.12"
mypy_path = "llm_sdk" 


[tool.uv.workspace]
members = ["llm_sdk"]
