[project]
name = "call"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SANTOOS00", email = "mohamederraiss@icloud.com" }
]
requires-python = ">=3.10"
dependencies = [
    "flake8>=7.3.0",
    "mypy>=2.3.1",
]

[project.scripts]
call = "call:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
